#!/system/bin/sh

# Teks ASCII
echo "  ____            _        _   __  __ _                  __  __ ____  _  _     _              _           _     _ "
echo " |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \| || |   / \   _ __   __| |_ __ ___ (_) __| |"
echo " | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) | || |_ / _ \ | '_ \ / _` | '__/ _ \| |/ _` |"
echo " |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/|__   _/ ___ \| | | | (_| | | | (_) | | (_| |"
echo " |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|      |_|/_/   \_\_| |_|\__,_|_|  \___/|_|\__,_|"
echo "                                                                                                                  "
echo "                                                                                                                  "
echo "                              https://github.com/TukangM/PocketMine-MP4Android                                    "
echo "                                   Made with AI generated chat.openai.com                                         "
echo "                      https://chat.openai.com/share/8f541b0c-947d-438a-a7c1-18ac00054a93                          "

# Variabel
OLD_PHAR="/data/local/pmmp/PocketMine-MP.phar"
NEW_PHAR_URL="https://github.com/pmmp/PocketMine-MP/releases/latest/download/PocketMine-MP.phar"

# Download the new PocketMine-MP.phar
wget -O "$OLD_PHAR.new" "$NEW_PHAR_URL"

# Check if the download was successful
if [ $? -eq 0 ]; then
    # Remove the old PocketMine-MP.phar
    rm -f "$OLD_PHAR"
    # Rename the new file to the old name
    mv "$OLD_PHAR.new" "$OLD_PHAR"
    echo "Update successful! PocketMine-MP.phar has been updated."
else
    echo "Update failed. Please check your internet connection and try again."
fi
